export const SET_LEFT_ARM_ANGLE = 'SET_LEFT_ARM_ANGLE'
export const SET_RIGHT_ARM_ANGLE = 'SET_RIGHT_ARM_ANGLE'
export const SET_LEFT_LEG_ANGLE = 'SET_LEFT_LEG_ANGLE'
export const SET_RIGHT_LEG_ANGLE = 'SET_RIGHT_LEG_ANGLE'
